### PR TITLE
feat: Support for historical time series data

### PR DESCRIPTION
**Pull request by arvindrajan92**
Hi @mindmelting, I am adding support for retrieving historical time series data without breaking `get_data()` method.

### CODE REVIEW

**Comment by mindmelting** [comment]
@arvindrajan92 thanks for the PR (and sorry for the delay!)

Would you mind adding to the README (and expanding the unit tests) to cover usage of `start`, `end` and `sample` arguments for the new method and example values for these?

(Also fixing up the failing flake8 lint errors!)

Thanks!

**Comment by arvindrajan92** [comment]
> @arvindrajan92 thanks for the PR (and sorry for the delay!)
> 
> Would you mind adding to the README (and expanding the unit tests) to cover usage of `start`, `end` and `sample` arguments for the new method and example values for these?
> 
> (Also fixing up the failing flake8 lint errors!)
> 
> Thanks!

@mindmelting no worries, and you're welcome :) 

I have expanded the unit test with more test cases and updated README.md. The flake8 lint errors should be fixed now. Please let me know if you get any more errors. Thanks

**Comment by arvindrajan92** [comment]
@mindmelting doesn't seem like an error I could fix from my end. hope you could take a look at it. thanks for spending some time looking into this - sincerely appreciate it :)

**Comment by mindmelting** [comment]
Will take a look this weekend, thanks!

**Comment by mindmelting** [comment]
@arvindrajan92 I have fixed the build issue - are you able to bump the version to `0.4.0` and I can then merge and publish it to pypi

**Comment by arvindrajan92** [comment]
> @arvindrajan92 I have fixed the build issue - are you able to bump the version to `0.4.0` and I can then merge and publish it to pypi

@mindmelting done :smile:

**Review by mindmelting — APPROVED** [review]

**Pull request merged**
